services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: game_backend
    working_dir: /app
    # start via flask CLI so FLASK_APP is respected
    command: flask run --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app:delegated
      - ./logs:/app/logs
    environment:
      FLASK_APP: backend/app.py
      FLASK_ENV: development
      MONGODB_URI: mongodb://mongodb:27017/game_db
      # pull SECRET_KEY from your host env, fallback to 'dev_key_123'
      SECRET_KEY: ${SECRET_KEY:-dev_key_123}
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: game_mongo
    # map container's 27017 → host's 27018 to avoid conflict
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: