version: '3.8'

services:
  web:
    build: .
    container_name: game_backend
    working_dir: /app
    command: python backend/app.py
    ports:
      - "8080:8080"
    volumes:
      - .:/app:delegated
      - ./logs:/app/logs
    environment:
      FLASK_ENV: development
      MONGODB_URI: mongodb://mongodb:27017/game_db
      SECRET_KEY: ${SECRET_KEY:-dev_key_123}
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: game_mongo
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: